# Generated by Django 5.2.3 on 2025-06-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "分类", "verbose_name_plural": "categories"},
        ),
    ]
