# Generated by Django 5.2.3 on 2025-06-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-publish",)},
        ),
    ]
